from .elevenlabs_nodes import NODE_CLASS_MAPPINGS as TTS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TTS_NAMES
from .float_to_int import NODE_CLASS_MAPPINGS as FTI_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FTI_NAMES

NODE_CLASS_MAPPINGS = {**TTS_MAPPINGS, **FTI_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**TTS_NAMES, **FTI_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
